In [ ]:
# ----------------------------TASK 1---------------------------------------
import pandas as pd
customer_data = {
    "ID":[101,102,103,104,105,106],
    "Name":["Ali","Sara","John","Aman","Riya","David"],
    "Age":[22,25,21,27,23,30]
}
df_1= pd.DataFrame(customer_data)

order_data = {
    "ID":[101,102,103,104,105,107],
    "Order":["Pizza","Burger","Pasta","Cold Coffee","Fries","Mojito"]
}
df_2= pd.DataFrame(order_data)

bill_data = {
    "ID":[101,102,103,104,105,106],
    "Bill":[450,220,380,180,150,500]
}
df_3= pd.DataFrame(bill_data)
# print(df_1)
# print(df_2)
# print(df_3)

In [31]:
# ----------------------------TASK 2---------------------------------------
print(df_1.info())
print(df_2.info())
print(df_3.info())
head_data= pd.concat([df_1,df_2,df_3], axis=1,ignore_index=False).head()
print(head_data)

tail_data= pd.concat([df_1,df_2,df_3], axis=1,ignore_index=False).tail()
print(tail_data)

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      str
 2   Age     6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Order   6 non-null      str
dtypes: int64(1), str(1)
memory usage: 228.0 bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Bill    6 non-null      int64
dtypes: int64(2)
memory usage: 228.0 bytes
None
    ID  Name  Age   ID        Order   ID  Bill
0  101   Ali   22  101        Pizza  101   450
1  102  Sara   25  102       Burger  102   220
2  103  John   21  103        Pasta  103   380
3  104  Aman   27  104  Cold Coffee  104   180
4  105  Riya   23  105        Fries  105   150
    ID   Name  Age   ID        Order   ID  Bill
1  102   Sara   25  102       Burger  102   220
2  103   John   21  103        Pasta  103   380
3  104   Aman   27  104  Cold Coffee  104   180
4  105   Riya   23  105        Fries  105   150
5  106  David   30  107       Mojito  106   500

In [32]:
# ----------------------------------TASK 3---------------------------------------------
print(f"Number of rows and columns in Table 1 = {df_1.shape}")
print(f"Number of rows and columns in Table 2 = {df_2.shape}")
print(f"Number of rows and columns in Table 3 = {df_3.shape}")
print(f"Column name and dtype in Table 1 = {df_1.columns}")
print(f"Column name and dtype in Table 2 = {df_2.columns}")
print(f"Column name and dtype in Table 3 = {df_3.columns}")

Number of rows and columns in Table 1 = (6, 3)
Number of rows and columns in Table 2 = (6, 2)
Number of rows and columns in Table 3 = (6, 2)
Column name and dtype in Table 1 = Index(['ID', 'Name', 'Age'], dtype='str')
Column name and dtype in Table 2 = Index(['ID', 'Order'], dtype='str')
Column name and dtype in Table 3 = Index(['ID', 'Bill'], dtype='str')

In [33]:
# ----------------------------------TASK 4-------------------------------
filtered_customer= df_1[df_1['Age']>23]
print(filtered_customer)

filtered_bills= df_3[df_3['Bill']>300]
print(filtered_bills)

filtered_customer_2= df_1[df_1['Age']<25]
print(filtered_customer_2)

    ID   Name  Age
1  102   Sara   25
3  104   Aman   27
5  106  David   30
    ID  Bill
0  101   450
2  103   380
5  106   500
    ID  Name  Age
0  101   Ali   22
2  103  John   21
4  105  Riya   23

In [34]:
# ------------------------------------TASK 5------------------------------------------
customer_order= pd.merge(left=df_1,right=df_2,how="inner",on='ID')
print(customer_order)

    ID  Name  Age        Order
0  101   Ali   22        Pizza
1  102  Sara   25       Burger
2  103  John   21        Pasta
3  104  Aman   27  Cold Coffee
4  105  Riya   23        Fries

In [35]:
# --------------------------------TASK 6-----------------------------------------------
customer_order_2= pd.merge(left=df_1,right=df_2,how='left',on='ID')
print(customer_order_2)
# the changes in customer David , ID 106 is that it does not have any order in the table as it follows left merge

    ID   Name  Age        Order
0  101    Ali   22        Pizza
1  102   Sara   25       Burger
2  103   John   21        Pasta
3  104   Aman   27  Cold Coffee
4  105   Riya   23        Fries
5  106  David   30          NaN

In [36]:
# ------------------------------------TASK 7---------------------------------------
customer_order_3= pd.merge(left=df_1,right=df_2,how='outer',on='ID')
print(customer_order_3)

    ID   Name   Age        Order
0  101    Ali  22.0        Pizza
1  102   Sara  25.0       Burger
2  103   John  21.0        Pasta
3  104   Aman  27.0  Cold Coffee
4  105   Riya  23.0        Fries
5  106  David  30.0          NaN
6  107    NaN   NaN       Mojito

In [37]:
# ----------------------------------TASK 8----------------------------------------------
resturant_df= pd.merge(left=customer_order_3,right=df_3,how='outer',on='ID')
print(resturant_df)

    ID   Name   Age        Order   Bill
0  101    Ali  22.0        Pizza  450.0
1  102   Sara  25.0       Burger  220.0
2  103   John  21.0        Pasta  380.0
3  104   Aman  27.0  Cold Coffee  180.0
4  105   Riya  23.0        Fries  150.0
5  106  David  30.0          NaN  500.0
6  107    NaN   NaN       Mojito    NaN

In [38]:
# ----------------------------------TASK 9------------------------------------------
new_customers = pd.DataFrame({
    "ID":[107,108],
    "Name":["Karan","Anjali"],
    "Age":[28,24]
})
pd.concat([resturant_df,new_customers],axis=0,ignore_index=True)

    ID    Name   Age        Order   Bill
0  101     Ali  22.0        Pizza  450.0
1  102    Sara  25.0       Burger  220.0
2  103    John  21.0        Pasta  380.0
3  104    Aman  27.0  Cold Coffee  180.0
4  105    Riya  23.0        Fries  150.0
5  106   David  30.0          NaN  500.0
6  107     NaN   NaN       Mojito    NaN
7  107   Karan  28.0          NaN    NaN
8  108  Anjali  24.0          NaN    NaN

In [ ]:
# ---------------------------------TASK 10----------------------------------------------print
print("Missing values are:")
print(resturant_df.isnull())
print(f"Number of missing values are: {resturant_df.isnull().sum()}")

resturant_df['Name']= resturant_df['Name'].fillna("Unknown")
resturant_df['Age']= resturant_df['Age'].fillna(0)
resturant_df['Order']= resturant_df['Order'].fillna("Unknown food")
resturant_df['Bill']= resturant_df['Bill'].fillna(0.0)

resturant_df

Missing values are:
      ID   Name    Age  Order   Bill
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False
5  False  False  False   True  False
6  False   True   True  False   True
Number of missing values are: ID       0
Name     1
Age      1
Order    1
Bill     1
dtype: int64

    ID     Name   Age         Order   Bill
0  101      Ali  22.0         Pizza  450.0
1  102     Sara  25.0        Burger  220.0
2  103     John  21.0         Pasta  380.0
3  104     Aman  27.0   Cold Coffee  180.0
4  105     Riya  23.0         Fries  150.0
5  106    David  30.0  Unknown food  500.0
6  107  Unknown   0.0        Mojito    0.0

<!-- The .values[0] cannot become value[1] b'coz of boolean mask -->
<!-- The boolean mask is find by:  -->
<!-- resturant_df.loc[resturant_df['Bill']==highest_bill,"ID"]  WHICH CHECKS-->
                                        450 == 500   → False
                                        220 == 500   → False
                                        380 == 500   → False
                                        180 == 500   → False
                                        150 == 500   → False
                                        500 == 500   → TRUE 
                                        0   == 500   → False
Now the .loc will only keep the True values's index and remove the False ones
<!-- that's why the .values contains only one index because only one value is true -->
customer_id= resturant_df.loc[resturant_df['Bill']==highest_bill,"ID"].values[0]

In [83]:
# -------------------------------FINAL ANALYSIS---------------------------------------------------
# Answer these questions using Pandas:

# Who paid the highest bill?
# Who is the youngest customer?
# Average bill?
# Maximum bill?
# Minimum bill?
# Total restaurant revenue?
# How many customers ordered Fries?
# How many customers are older than 24?

highest_bill= resturant_df['Bill'].max()
customer_id= resturant_df.loc[resturant_df['Bill']==highest_bill,"ID"].values[0]
print(f'Customer {customer_id} paid highest bill.')

youngest_customer= resturant_df['Age'].min()
customer_name= resturant_df.loc[resturant_df['Age']==youngest_customer,"Name"].values[0]
print(f'{customer_name} is the youngest customer')

avg_bill= resturant_df['Bill'].mean()
print(f'Avg. bill is {round(avg_bill,2)}.')  # THE round(value, significant_figures) WILL REDUCE DECIMAL FIG.

max_bill= resturant_df['Bill'].max()
print(f'Max. bill is {max_bill}.')

min_bill= resturant_df['Bill'].min()
print(f'Min. bill is {min_bill}.')

total_revenue= resturant_df['Bill'].sum()
print(f'Total revenue is {total_revenue}.')

# for i in range(0,,)
fries_customer= (resturant_df['Order']=="Fries").value_counts(sort=False)  
# [----.value_counts()----] Return the frequencies of bool values when something is compared & SORT=FALSE will 1st return frequency of True values then False
# for key, value in fries_customer.items():
#     print(key, value)
print(f'Customers ordered Fries are {fries_customer[True]}.')

older_than_24= (resturant_df['Age']>24).sum()
print(f'customers older than 24 are {older_than_24}.')

Customer 106 paid highest bill.
Unknown is the youngest customer
Avg. bill is 268.57.
Max. bill is 500.0.
Min. bill is 0.0.
Total revenue is 1880.0.
Customers ordered Fries are 1.
customers older than 24 are 3.

In [91]:
# Restaurant Report

# Total Customers :
# Average Age :
# Average Bill :
# Highest Bill :
# Lowest Bill :
# Revenue :

total_customers= resturant_df.shape
print(f'Total customers are {total_customers[0]}')

average_age= resturant_df['Age'].mean()
print(f'Average Age :{round(average_age, 0)}')

avg_bill= resturant_df['Bill'].mean()
print(f'Average bill : {round(avg_bill,2)}.')  # THE round(value, significant_figures) WILL REDUCE DECIMAL FIG.

highest_bill_2= resturant_df['Bill'].max()
print(f'Highest Bill :{highest_bill_2}')

lowest_bill= resturant_df['Bill'].min()
print(f'Lowest Bill :{lowest_bill}')

print(f'Revenue :{total_revenue}')

Total customers are 7
Average Age :21.0
Average bill : 268.57.
Highest Bill :500.0
Lowest Bill :0.0
Revenue :1880.0